name: xerosix
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56954
title: x e r o s i x
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#323031'
    - '#625e5d'
    - '#bfb9b9'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
